DROP TABLE user_roles IF EXISTS;
DROP TABLE meals IF EXISTS;
DROP TABLE users IF EXISTS;
DROP SEQUENCE global_seq IF EXISTS;

CREATE SEQUENCE GLOBAL_SEQ
  AS INTEGER
  START WITH 100000;

CREATE TABLE users
(
  id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  name             VARCHAR(255)                 NOT NULL,
  email            VARCHAR(255)                 NOT NULL,
  password         VARCHAR(255)                 NOT NULL,
  registered       TIMESTAMP DEFAULT now() NOT NULL,
  enabled          BOOL DEFAULT TRUE       NOT NULL,
  secondName       VARCHAR(255)                         ,
  firstName        VARCHAR(255)                         ,
  datetime         TIMESTAMP DEFAULT now()         ,
  phoneNumber      VARCHAR(255)
);
CREATE UNIQUE INDEX users_unique_email_idx
  ON USERS (email);

CREATE TABLE user_roles
(
  user_id INTEGER NOT NULL,
  role    VARCHAR(255),
  CONSTRAINT user_roles_idx UNIQUE (user_id, role),
  FOREIGN KEY (user_id) REFERENCES USERS (id) ON DELETE CASCADE
);

CREATE TABLE bets (
  id          INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  user_id     INTEGER   NOT NULL,
  date_time   TIMESTAMP NOT NULL,
  value       NUMERIC (20,3) NOT NULL,
  coefficient NUMERIC (20,3)  NOT NULL,
  currency    TEXT      NOT NULL,
  event       TEXT      NOT NULL,
  net_profit  NUMERIC (20,3)        ,
  return_sum  NUMERIC (20,3)        ,
  is_express  BOOL DEFAULT FALSE ,
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX bets_unique_user_datetime_idx
  ON bets (user_id, date_time);